name: Generate README

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v3

    - name: Setup Deno
      uses: denoland/setup-deno@v1.1.2

    - name: Generate README.md
      run: deno task generate

    - name: Format
      run: deno fmt
